/* AUTO-GENERATED by Kyusei-edit-bot
   * Do not edit manually if you use the bot.
   */

var PRODUCTS = [
  {
    "code": "B002",
    "name": "Najay",
    "game": "ml",
    "price": 1,
    "sold": false,
    "detail": [
      "Anjai",
      "Anjai"
    ],
    "images": [
      "assets/products/ml/B002/1.jpg"
    ]
  }
];
